defmodule ExLingo.PoFiles.POExporter do
  @moduledoc """
  Mirrors the translations stored in the database back into gettext `.po`
  files, one per locale + domain (`<locale>/LC_MESSAGES/<domain>.po`).

  Uses `Expo.PO.compose/1` — the same library ExLingo uses to read PO files —
  so no extra dependency is needed. Singular messages round-trip exactly
  (`msgid` is the source key, `msgstr` is the stored translation).

  Plural messages carry the source plural form (`msgid_plural`), captured on
  import, with the per-form translations as `msgstr[i]`. Messages imported
  before that capture existed fall back to `msgid` (it is regenerated by
  `mix gettext.extract` anyway).
  """

  alias ExLingo.Translations
  alias ExLingo.Translations.PluralTranslations.Finders.ListPluralTranslations
  alias ExLingo.Translations.SingularTranslations.Finders.ListSingularTranslations
  alias Expo.Message.{Plural, Singular}
  alias Expo.{Messages, PO}

  @default_domain "default"
  @no_context "default"
  @zip_name ~c"ex_lingo_translations.zip"

  @type file :: %{path: String.t(), content: binary()}

  @doc """
  Returns one entry per locale + domain that has messages:
  `%{path: "de/LC_MESSAGES/default.po", content: <po binary>}`.
  """
  @spec export_files() :: [file()]
  def export_files do
    for locale <- all_locales(),
        {domain, messages} <- messages_by_domain(locale),
        messages != [] do
      %{
        path: po_path(locale.iso639_code, domain),
        content: locale |> compose(messages) |> IO.iodata_to_binary()
      }
    end
  end

  @doc """
  Packs `export_files/0` into a single in-memory ZIP (gettext directory layout
  preserved). Returns `{:ok, binary}` or `{:error, reason}`.
  """
  @spec export_zip() :: {:ok, binary()} | {:error, term()}
  def export_zip do
    entries =
      Enum.map(export_files(), fn %{path: path, content: content} ->
        {String.to_charlist(path), content}
      end)

    case :zip.create(@zip_name, entries, [:memory]) do
      {:ok, {_name, binary}} -> {:ok, binary}
      {:error, _reason} = error -> error
    end
  end

  defp all_locales do
    %{entries: locales} = Translations.list_locales(per_page: 1000)
    locales
  end

  defp messages_by_domain(locale) do
    locale_id = to_string(locale.id)
    singular_query = ListSingularTranslations.filter_query(%{"locale_id" => locale_id})
    plural_query = ListPluralTranslations.filter_query(%{"locale_id" => locale_id})

    Translations.list_all_messages(
      preloads: [
        :domain,
        singular_translations: singular_query,
        plural_translations: plural_query
      ]
    )
    |> Enum.group_by(&domain_name/1)
  end

  defp domain_name(%{domain: %{name: name}}) when is_binary(name) and name != "", do: name
  defp domain_name(_message), do: @default_domain

  defp compose(locale, messages) do
    %Messages{
      headers: headers(locale),
      messages: Enum.map(messages, &to_expo_message/1)
    }
    |> PO.compose()
  end

  defp headers(locale) do
    ["Language: #{locale.iso639_code}\n"] ++ plural_forms_header(locale)
  end

  defp plural_forms_header(%{plurals_header: header}) when is_binary(header) and header != "" do
    ["Plural-Forms: #{header}\n"]
  end

  defp plural_forms_header(_locale), do: []

  defp to_expo_message(%{message_type: :singular} = message) do
    %Singular{
      msgid: [message.msgid],
      msgstr: [singular_msgstr(message)],
      msgctxt: msgctxt(message),
      references: references(message)
    }
  end

  defp to_expo_message(%{message_type: :plural} = message) do
    %Plural{
      msgid: [message.msgid],
      msgid_plural: [plural_source(message)],
      msgstr: plural_msgstr(message),
      msgctxt: msgctxt(message),
      references: references(message)
    }
  end

  # Use the stored source plural form; fall back to msgid for messages imported
  # before it was captured (it is regenerated by `mix gettext.extract` anyway).
  defp plural_source(%{msgid_plural: msgid_plural})
       when is_binary(msgid_plural) and msgid_plural != "",
       do: msgid_plural

  defp plural_source(message), do: message.msgid

  defp singular_msgstr(%{singular_translations: [translation | _]}), do: text_for(translation)
  defp singular_msgstr(_message), do: ""

  defp plural_msgstr(%{plural_translations: translations}) do
    translations
    |> Enum.sort_by(& &1.nplural_index)
    |> Map.new(fn translation -> {translation.nplural_index, [text_for(translation)]} end)
    |> ensure_zero_index()
  end

  # A plural message must have at least msgstr[0] to be valid.
  defp ensure_zero_index(map) when map_size(map) == 0, do: %{0 => [""]}
  defp ensure_zero_index(map), do: map

  defp text_for(%{translated_text: translated, original_text: original}) do
    cond do
      present?(translated) -> translated
      present?(original) -> original
      true -> ""
    end
  end

  defp msgctxt(%{context: context}) when context in [nil, "", @no_context], do: nil
  defp msgctxt(%{context: context}), do: [context]

  defp references(%{source_references: references})
       when is_list(references) and references != [] do
    line =
      Enum.flat_map(references, fn
        %{"file" => file, "line" => line} when is_integer(line) -> [{file, line}]
        %{"file" => file} -> [file]
        _other -> []
      end)

    if line == [], do: [], else: [line]
  end

  defp references(_message), do: []

  defp po_path(locale_code, domain), do: "#{locale_code}/LC_MESSAGES/#{domain}.po"

  defp present?(value), do: is_binary(value) and String.trim(value) != ""
end
